/**
 * Temporary sample book data used until scanner persistence is implemented.
 */

import type { BookDetail, BookSummary } from "@bookcafe/core";

export const sampleBooks: BookDetail[] = [
  {
    id: "sample-manga",
    title: "Sample Manga",
    authors: ["BookCafe"],
    format: "image-folder",
    status: "ready",
    readingStatus: "unread",
    tags: ["sample"],
    pageCount: 12,
    currentPage: 1,
    thumbnailUrl: "/api/books/sample-manga/pages/1/image",
    sourcePath: "fixtures/books/sample-manga",
    readingDirection: "rtl",
    publisher: null,
    isbn: null,
    purchasedAt: null,
    notes: null
  }
];

/**
 * Returns summaries for all sample books.
 */
export const listSampleBooks = (): BookSummary[] =>
  sampleBooks.map((book) => ({
    id: book.id,
    title: book.title,
    authors: book.authors,
    format: book.format,
    status: book.status,
    readingStatus: book.readingStatus,
    tags: book.tags,
    pageCount: book.pageCount,
    currentPage: book.currentPage,
    thumbnailUrl: book.thumbnailUrl
  }));

/**
 * Finds a sample book by id.
 */
export const findSampleBook = (bookId: string): BookDetail | null =>
  sampleBooks.find((book) => book.id === bookId) ?? null;

/**
 * Renders a lightweight SVG placeholder page.
 */
export const renderSamplePageSvg = (book: BookDetail, page: number): string => {
  const safeTitle = escapeXml(book.title);
  const hue = (page * 29) % 360;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="960" height="1440" viewBox="0 0 960 1440" role="img" aria-labelledby="title desc">
  <title id="title">${safeTitle} page ${page}</title>
  <desc id="desc">Placeholder page generated by BookCafe.</desc>
  <rect width="960" height="1440" fill="hsl(${hue} 38% 18%)"/>
  <rect x="72" y="72" width="816" height="1296" rx="16" fill="hsl(${hue} 45% 92%)"/>
  <text x="480" y="560" text-anchor="middle" font-family="system-ui, sans-serif" font-size="64" font-weight="700" fill="hsl(${hue} 48% 20%)">${safeTitle}</text>
  <text x="480" y="680" text-anchor="middle" font-family="system-ui, sans-serif" font-size="48" fill="hsl(${hue} 40% 28%)">Page ${page} / ${book.pageCount}</text>
  <path d="M220 930 C310 820 430 820 520 930 S730 1040 800 930" fill="none" stroke="hsl(${hue} 48% 35%)" stroke-width="18" stroke-linecap="round"/>
</svg>`;
};

/**
 * Escapes text for XML output.
 */
const escapeXml = (value: string): string =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
